dist: trusty
sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"
before_install:
    - pip install --upgrade setuptools pip
    - pip install --upgrade virtualenv
install:
    - pip --version
    - virtualenv --version
    - git --version
before_script:
    - pip install --upgrade flake8 pylint codecov
    - pip install --upgrade pytest-flake8 pytest-pylint pytest-cov
script:
    - python -m pytest
after_success:
    - codecov
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: mozillasecurity
    password:
        secure: g6uQXecN2eljSylJVgHNc4sZgg6NL7VIIpKO+aSTQ3bpgDsFIWKZlifoIH9ns9gaWtT639ObZlgLoCy6benGMs6mX24ki/RwRTEe5INaj3FG0fNRQRoYYoEZQAUJBT0YSoyil2TuFSL2iDGoMUt/w2GDXY2RID1M+rMP/EucSV/IadiNCfT2a6rjol7SMt9/jg0CL1KTENj801XdSiUiaGZqLmKf2QmfRFET9LsKYM8CdPjJGC4QcwvOHEgd82ub2WdFBBUhw4Qirit+BakZuaoyRWSc84tryaKhFYXTJDWUWxLBIV9LXQW1+S038stwVBrwMwh1O+df49II44hIBakV/vPgosDHQ9/6+hw84gsmtvSLkrmKpXxVd28zlNC2mH946qAB/g8OLmXyiyla6GlKS2GwgYrQYypj7Pv+kzru4l6DTGNwJKwF6eAx160ixnH+VOAXD5aBNeqnJ0fcBpnmNaUM2OB3IwYMWhDtgGpJNXX9tiaRKkvsZuBwO4wXZu/CtZHnGMou35lQGDk8ypMBsTGI4lfHLaZT9+bq6qq5hwAMgqjLbRcHiTafWPiczD4kZtQ76MKKMJzPmwptE6npgeFd25nz76l2iZyC+b9zeyynwEHOtwcuR6JWQd2lDwv4uCfhHzPsLX3K1Z3y6kXmDmm4PMxVCoXjgnw1lGQ=
    on:
        tags: true
