dist: trusty
sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"
before_install:
    - pip install --upgrade setuptools pip
    - pip install --upgrade virtualenv
install:
    - pip --version
    - virtualenv --version
    - git --version
before_script:
    - pip install --upgrade flake8 pylint codecov
    - pip install --upgrade pytest-flake8 pytest-pylint pytest-cov
script:
    - python -m pytest
after_success:
    - codecov
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: mozillasecurity
    password:
        secure: NfLYqeHf+jD0A3mVkA/wgx3av5ofXpSw8nNJ5sM02vvjVmtgMpK8MN9L7CeJ3uJp11uJVAX89DBuSNV78GS8Bt0FJBIPhlb9Ax+IUnqvjzXCc0Uwa7g9jF3MRBC/+iSdIF1qkCpvH4mTCOSq8CRvPC7idJxU12e8pjlu9sJVSKm6oEDDgh1pde55Eh3qej6n9Mv1MI4bYw1TqhbOZX0ykebToM8J4zM4bCO/FwHJlrgvLW6IwEkhkZpqPc+tJgxGBsmTiD45bwAmwrOwe+Ynze/fTwq5/9J5dXNATIeZt8I+75Cla8GgA+eoaZyxraGqdIMHuHno3rREXCv4hG2JOw2wfSeC8uPcFeDRDVau8kZirQXUAIdHgs7sqDanDJIw/hGJ4PiqfnzvCdK1pcXSoedkRYEsOEaPvO4nVm3yDmwAsctCVwjGqOSn5H/EXjWAPHbi51uo0pxg8NR6CtuYZQuZEYkSSaMak5FZm6/QI6oIeeaXQiFzmHxUHI2qbGJ091q6qOo07OLcPIW6cT3mkMyQAdAsXZbki4lHYL/KfHNko8yU4ez8m54aLyymer7uCDLI5KpGKQa2Sk7CSgHwsO97Sx/jbKbBx83UKeklJk4iTaHRCQx4AgFqcH5/fK2K84nN06MzGQUwpXa0JG+Y/LvaLFYvMo1LT4l8bmEeLJw=
    on:
        tags: true
